spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://mysql:3306/demo
        username: root
        password: teleri
        driver-class-name: com.mysql.jdbc.Driver